apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: flask-app-monitor
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: flask-app

  namespaceSelector:
    matchNames:
      - flask-app

  endpoints:
    - port: flask-service
      path: /metrics
      interval: 15s
